In [1]:
# YOUR CODE HERE
import pandas as pd

# get the data
hotels = pd.read_csv("C:/Users/jhb_f/Desktop/Fall 2017 B/Programming/data/hotels.txt")
print(len(hotels))

366644

In [2]:
# YOUR CODE HERE
hotels.dtypes
hotels[['hotel_code', 'location_code']] = hotels[['hotel_code', 'location_code']].astype(str)
hotels.dtypes

hotel_code                   object
country_code                 object
country_name                 object
location_code                object
location_name                object
hotel_type                   object
rooms                       float64
bubble_rating               float64
bubble_one                    int64
bubble_two                    int64
bubble_three                  int64
bubble_four                   int64
bubble_five                   int64
page_position               float64
out_of                      float64
reviews                       int64
domestic_reviews              int64
international_reviews         int64
reviews_per_room            float64
visitor_country1             object
visitor_country2             object
visitor_country3             object
management_response_rate    float64
independent_flag              int64
traffic                     float64
traffic_per_room            float64
OTA_region_rate             float64
subscriber                    int64
hotel                         int64
BandB                         int64
Specialty                     int64
dtype: object

In [4]:
# YOUR CODE HERE
import numpy as np

#select only numeric colunms
hotelsnum = hotels.select_dtypes(exclude=['object'])

#assign outlers 
hotels_outliers = ((hotelsnum < (hotelsnum.mean() - 3 * hotelsnum.std())) 
                   | (hotelsnum > (hotelsnum.mean() + 3 * hotelsnum.std())))

#replace outliers to nan
hotelsnum1 = hotelsnum[hotelsnum.columns]
hotelsnum1[hotels_outliers] = np.nan

print(hotelsnum1.isnull().sum())
print(hotelsnum1.describe())

rooms                       36105
bubble_rating               25617
bubble_one                   3751
bubble_two                   4379
bubble_three                 4700
bubble_four                  5330
bubble_five                  4859
page_position                6466
out_of                       7852
reviews                      5056
domestic_reviews             4948
international_reviews        4512
reviews_per_room            36856
management_response_rate    35050
independent_flag             8285
traffic                      3795
traffic_per_room            34431
OTA_region_rate              5355
subscriber                      0
hotel                           0
BandB                           0
Specialty                       0
dtype: int64
               rooms  bubble_rating     bubble_one     bubble_two  \
count  330539.000000  341027.000000  362893.000000  362265.000000
mean       44.751821       3.948309       2.244246       2.448252
std        61.730329       0.773631       4.783912       4.889694
min         1.000000       1.500000       0.000000       0.000000
25%         8.000000       3.500000       0.000000       0.000000
50%        20.000000       4.000000       0.000000       1.000000
75%        50.000000       4.500000       2.000000       3.000000
max       337.000000       5.000000      39.000000      37.000000

        bubble_three    bubble_four    bubble_five  page_position  \
count  361944.000000  361314.000000  361785.000000  360178.000000
mean        5.281055      12.910837      19.823039      29.696531
std        10.006515      23.083421      37.269800      67.779115
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       1.000000       1.000000       1.000000
50%         1.000000       4.000000       5.000000       5.000000
75%         5.000000      13.000000      20.000000      23.000000
max        74.000000     167.000000     274.000000     561.000000

              out_of        reviews      ...        reviews_per_room  \
count  358792.000000  361588.000000      ...           329788.000000
mean       81.747550      47.024735      ...                2.771017
std       172.171794      81.349949      ...                4.700747
min         1.000000       0.000000      ...                0.000000
25%         5.000000       4.000000      ...                0.200000
50%        19.000000      16.000000      ...                0.842105
75%        70.000000      50.000000      ...                3.000000
max      1376.000000     608.000000      ...               31.222222

       management_response_rate  independent_flag        traffic  \
count             331594.000000          358359.0  362849.000000
mean                   0.030155               1.0    5079.148423
std                    0.070508               0.0    9582.768289
min                    0.000000               1.0       1.000000
25%                    0.000000               1.0     663.000000
50%                    0.000000               1.0    1718.000000
75%                    0.008969               1.0    4827.000000
max                    0.348684               1.0   84750.000000

       traffic_per_room  OTA_region_rate     subscriber          hotel  \
count     332213.000000    361289.000000  366644.000000  366644.000000
mean         259.536682       119.264723       0.128012       0.502997
std          423.194564        40.159137       0.334104       0.499992
min            0.044000        21.770000       0.000000       0.000000
25%           36.333333        92.439216       0.000000       0.000000
50%          104.312500       121.949369       0.000000       1.000000
75%          287.466667       132.856667       0.000000       1.000000
max         3547.200000       268.606364       1.000000       1.000000

               BandB      Specialty
count  366644.000000  366644.000000
mean        0.326404       0.170599
std         0.468898       0.376158
min         0.000000       0.000000
25%         0.000000       0.000000
50%         0.000000       0.000000
75%         1.000000       0.000000
max         1.000000       1.000000

[8 rows x 22 columns]

In [7]:
print(hotelsnum1.isnull().sum())
print(hotels.isnull().sum())

rooms                       36105
bubble_rating               25617
bubble_one                   3751
bubble_two                   4379
bubble_three                 4700
bubble_four                  5330
bubble_five                  4859
page_position                6466
out_of                       7852
reviews                      5056
domestic_reviews             4948
international_reviews        4512
reviews_per_room            36856
management_response_rate    35050
independent_flag             8285
traffic                      3795
traffic_per_room            34431
OTA_region_rate              5355
subscriber                      0
hotel                           0
BandB                           0
Specialty                       0
dtype: int64
hotel_code                      0
country_code                    0
country_name                    0
location_code                   0
location_name                   0
hotel_type                      0
rooms                       31421
bubble_rating               22518
bubble_one                      0
bubble_two                      0
bubble_three                    0
bubble_four                     0
bubble_five                     0
page_position                  42
out_of                         42
reviews                         0
domestic_reviews                0
international_reviews           0
reviews_per_room            31421
visitor_country1                0
visitor_country2                0
visitor_country3                0
management_response_rate    22363
independent_flag                0
traffic                         2
traffic_per_room            31423
OTA_region_rate                 0
subscriber                      0
hotel                           0
BandB                           0
Specialty                       0
dtype: int64

In [5]:
# YOUR CODE HERE
hotelsnum2 = hotelsnum1.fillna(hotelsnum1.mean())

print(hotelsnum2.isnull().sum())
print(hotelsnum2.describe())

rooms                       0
bubble_rating               0
bubble_one                  0
bubble_two                  0
bubble_three                0
bubble_four                 0
bubble_five                 0
page_position               0
out_of                      0
reviews                     0
domestic_reviews            0
international_reviews       0
reviews_per_room            0
management_response_rate    0
independent_flag            0
traffic                     0
traffic_per_room            0
OTA_region_rate             0
subscriber                  0
hotel                       0
BandB                       0
Specialty                   0
dtype: int64
               rooms  bubble_rating     bubble_one     bubble_two  \
count  366644.000000  366644.000000  366644.000000  366644.000000
mean       44.751821       3.948309       2.244246       2.448252
std        58.612142       0.746115       4.759378       4.860406
min         1.000000       1.500000       0.000000       0.000000
25%         9.000000       3.500000       0.000000       0.000000
50%        24.000000       4.000000       0.000000       1.000000
75%        45.000000       4.500000       2.000000       2.448252
max       337.000000       5.000000      39.000000      37.000000

        bubble_three    bubble_four    bubble_five  page_position  \
count  366644.000000  366644.000000  366644.000000  366644.000000
mean        5.281055      12.910837      19.823039      29.696531
std         9.942171      22.915022      37.022014      67.178791
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       1.000000       1.000000       2.000000
50%         2.000000       4.000000       5.000000       6.000000
75%         5.281055      13.000000      20.000000      25.000000
max        74.000000     167.000000     274.000000     561.000000

              out_of        reviews      ...        reviews_per_room  \
count  366644.000000  366644.000000      ...           366644.000000
mean       81.747550      47.024735      ...                2.771017
std       170.318207      80.787095      ...                4.458224
min         1.000000       0.000000      ...                0.000000
25%         5.000000       5.000000      ...                0.250000
50%        20.000000      16.000000      ...                1.116667
75%        75.000000      49.000000      ...                2.771017
max      1376.000000     608.000000      ...               31.222222

       management_response_rate  independent_flag        traffic  \
count             366644.000000          366644.0  366644.000000
mean                   0.030155               1.0    5079.148423
std                    0.067054               0.0    9533.045260
min                    0.000000               1.0       1.000000
25%                    0.000000               1.0     670.000000
50%                    0.000000               1.0    1751.000000
75%                    0.030155               1.0    5023.000000
max                    0.348684               1.0   84750.000000

       traffic_per_room  OTA_region_rate     subscriber          hotel  \
count     366644.000000    366644.000000  366644.000000  366644.000000
mean         259.536682       119.264723       0.128012       0.502997
std          402.833926        39.864786       0.334104       0.499992
min            0.044000        21.770000       0.000000       0.000000
25%           41.136223        92.986825       0.000000       0.000000
50%          127.500000       120.835455       0.000000       1.000000
75%          259.536682       132.530000       0.000000       1.000000
max         3547.200000       268.606364       1.000000       1.000000

               BandB      Specialty
count  366644.000000  366644.000000
mean        0.326404       0.170599
std         0.468898       0.376158
min         0.000000       0.000000
25%         0.000000       0.000000
50%         0.000000       0.000000
75%         1.000000       0.000000
max         1.000000       1.000000

[8 rows x 22 columns]

In [7]:
# YOUR CODE HERE
hotelsnum2.agg(['mean','std','skew','kurtosis'])

,rooms,bubble_rating,bubble_one,bubble_two,bubble_three,bubble_four,bubble_five,page_position,out_of,reviews,...,reviews_per_room,management_response_rate,independent_flag,traffic,traffic_per_room,OTA_region_rate,subscriber,hotel,BandB,Specialty
mean,44.751821,3.948309,2.244246,2.448252,5.281055,12.910837,19.823039,29.696531,81.747550,47.024735,...,2.771017,0.030155,1.0,5079.148423,259.536682,119.264723,0.128012,0.502997,0.326404,0.170599
std,58.612142,0.746115,4.759378,4.860406,9.942171,22.915022,37.022014,67.178791,170.318207,80.787095,...,4.458224,0.067054,0.0,9533.045260,402.833926,39.864786,0.334104,0.499992,0.468898,0.376158
skew,2.525254,-0.723099,3.777336,3.506091,3.427976,3.331640,3.357492,4.174329,3.951997,3.325834,...,3.099484,2.823163,0.0,4.132357,3.684008,0.731041,2.226788,-0.011990,0.740448,1.751406
kurtosis,6.783923,0.435141,17.361277,14.677153,13.865527,13.004220,13.256232,20.225867,18.391919,13.198286,...,11.234673,7.616600,0.0,21.039066,17.403820,1.058140,2.958602,-1.999867,-1.451745,1.067428

SyntaxError: can't assign to function call (<ipython-input-10-09dac8970776>, line 1)

hotel_code                      0
country_code                    0
country_name                    0
location_code                   0
location_name                   0
hotel_type                      0
rooms                       31421
bubble_rating               22518
bubble_one                      0
bubble_two                      0
bubble_three                    0
bubble_four                     0
bubble_five                     0
page_position                  42
out_of                         42
reviews                         0
domestic_reviews                0
international_reviews           0
reviews_per_room            31421
visitor_country1                0
visitor_country2                0
visitor_country3                0
management_response_rate    22363
independent_flag                0
traffic                         2
traffic_per_room            31423
OTA_region_rate                 0
subscriber                      0
hotel                           0
BandB                           0
Specialty                       0
dtype: int64

In [6]:
hotels.update(hotelsnum2)

In [7]:
print(hotels.isnull().sum())

hotel_code                  0
country_code                0
country_name                0
location_code               0
location_name               0
hotel_type                  0
rooms                       0
bubble_rating               0
bubble_one                  0
bubble_two                  0
bubble_three                0
bubble_four                 0
bubble_five                 0
page_position               0
out_of                      0
reviews                     0
domestic_reviews            0
international_reviews       0
reviews_per_room            0
visitor_country1            0
visitor_country2            0
visitor_country3            0
management_response_rate    0
independent_flag            0
traffic                     0
traffic_per_room            0
OTA_region_rate             0
subscriber                  0
hotel                       0
BandB                       0
Specialty                   0
dtype: int64

In [9]:
hotels.to_csv('hotels_scrubbed.csv', sep=',')

In [8]:
hotels.dtypes

hotel_code                   object
country_code                 object
country_name                 object
location_code                object
location_name                object
hotel_type                   object
rooms                       float64
bubble_rating               float64
bubble_one                  float64
bubble_two                  float64
bubble_three                float64
bubble_four                 float64
bubble_five                 float64
page_position               float64
out_of                      float64
reviews                     float64
domestic_reviews            float64
international_reviews       float64
reviews_per_room            float64
visitor_country1             object
visitor_country2             object
visitor_country3             object
management_response_rate    float64
independent_flag            float64
traffic                     float64
traffic_per_room            float64
OTA_region_rate             float64
subscriber                    int64
hotel                         int64
BandB                         int64
Specialty                     int64
dtype: object